numpy:\

* genral purpose array - processing language

* high-performance multidimensional array object, and tools for working with these arrays.

In [ ]:
import numpy as n

In [ ]:
#creating in numpy array
lst=[1,2,3,45,6,6]
ar=n.array(lst)
ar.dtype


dtype('int64')

In [ ]:
import pandas as pd
nd=n.array([1,2,3,4,5])
nf=pd.Series(nd)
nf

0    1
1    2
2    3
3    4
4    5
dtype: int64

**Reshape**
 * returns the array with new shape with same data

In [ ]:
ar.reshape(3,2)

array([[ 1,  2],
       [ 3, 45],
       [ 6,  6]])

**Broadcasting**

In [ ]:
ar1=n.array([[12,3,5,3],[3,3,5,9]])
ar1.max()



12

In [ ]:
ar1.ndim()

In [ ]:
ar1.min()

3

In [ ]:
ar1.argmax() #returns the index of max() value

0

In [ ]:
ar1.argmin()  #returns the index of min() value

1

In [ ]:
# n.arange(1,10)    #for print range() using arange
m=n.arange(1,12,2)
m.reshape(3,2)


array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
#for creating zeros
n.zeros(5)
n.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
m1=n.zeros((3,5))
mm=m1.shape[0] # no.of row
mm=m1.shape[1] #no.of col
mm

5

In [ ]:
#for creating ones
n.ones(5)      #o/p  :  array([1., 1., 1., 1., 1.])
n.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
 #for seprating values (divide what i want )
 n.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [ ]:
#for creating matrix form 5=[5,5] or 7=[7,7]
n.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
 #creat 4,4 matrix and reshape 2,2
m=n.eye(4)
m=m.reshape(2,8)
print(m)
p=m.shape
print(p)



[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]
(2, 8)


**random:**
 * for creating random numbers
 * we can create random matrix also
 * for random valuve within 0 use rand(),
   for 1 to 10 use randint(1,10,5),
   for random syntax value rand(3,4)

In [ ]:
#for creating random numbers using rand()---used for 0 to 1 random num
n.random.rand(5)

array([0.71465572, 0.84063747, 0.19505752, 0.56719419, 0.58947501])

In [ ]:
n.random.rand(5,5,2)  #for random matrix

array([[[0.31664804, 0.35172024],
        [0.69701504, 0.70040445],
        [0.18718851, 0.66843371],
        [0.79838791, 0.30428186],
        [0.58676554, 0.97469501]],

       [[0.32041005, 0.50652282],
        [0.56124383, 0.70687318],
        [0.08669308, 0.26490425],
        [0.59385946, 0.07491937],
        [0.92709478, 0.83712207]],

       [[0.49217914, 0.63214834],
        [0.138518  , 0.27572339],
        [0.64971776, 0.04126577],
        [0.07550961, 0.20585628],
        [0.85881109, 0.78773834]],

       [[0.2685448 , 0.11861636],
        [0.57964027, 0.88683187],
        [0.57735062, 0.46862432],
        [0.89332363, 0.3641132 ],
        [0.13031031, 0.12830617]],

       [[0.19886744, 0.76848073],
        [0.13034452, 0.45207578],
        [0.00225192, 0.88041996],
        [0.05872866, 0.51257524],
        [0.25859469, 0.03456599]]])

In [ ]:
#for crearing random number 1 to -----
n.random.randint(2,20,4)

array([ 6, 17, 15,  7])

In [ ]:
n.random.randn(4) # including (-) value

array([ 0.57685019, -1.09192161,  1.48770723,  1.71927216])

In [ ]:
#practice

In [ ]:
lst=[1,2,3,[45,6]]
ar=n.array(lst)
ar.reshape(2,2)

<ipython-input-77-4bf34035cdd5>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar=n.array(lst)


array([[1, 2],
       [3, list([45, 6])]], dtype=object)

In [ ]:
s_ar=n.array(['h','a','r','i'])
s_ar.reshape(2,2)

array([['h', 'a'],
       ['r', 'i']], dtype='<U1')