In [ ]:
import numpy as np

In [ ]:
n=np.arange(1,11)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

***....indexing....***

In [ ]:
n[3]

4

In [ ]:
n[1:7]
n[-5:]

array([45,  7,  8,  9, 10])

In [ ]:

lst=[1,2,3,4,6,7,8]
lst[::-1]

[8, 7, 6, 4, 3, 2, 1]

***broadcasting***

In [ ]:
ar1=n[:6]
ar1[:]=45
ar1

array([45, 45, 45, 45, 45, 45])

In [ ]:
n
 # memory errror : i took slicing array and stored another variable(ar1) and changed the value of (ar1)... it change the orginal array value of(n)
 # solution : shallow copy medhode

array([45, 45, 45, 45, 45, 45,  7,  8,  9, 10])

In [ ]:
ar2=n[:5].copy()
ar2[:]=[3,4,5,7,8]
ar1
ar3=n[:5].copy()
ar3[:]=[3,4,5,7,8]
ar3

array([3, 4, 5, 7, 8])

In [ ]:
n


[ 1  2  3  4  5  6  7  8  9 10]


array([3, 4, 5, 7, 8])

**indexing 2D array(matrixes).....**

In [ ]:
m1=np.array([ [1,2,3,4],[5,6,7,8],[9,9,7,5] , [5,6,3,6] ])

In [ ]:
m1

In [ ]:
m1.reshape(2,8)

array([[1, 2, 3, 4, 5, 5, 5, 8],
       [9, 5, 5, 5, 5, 6, 3, 6]])

In [ ]:
m1.shape

(4, 4)

In [ ]:
m1[1,3] #acces accesing the  value in 2d array
m1[1][3]

8

In [ ]:
m1[1:3,1:3] #slicing

array([[6, 7],
       [9, 7]])

In [ ]:
m2=m1[1:3,1:3].copy()
m2[:]=4
m2

array([[4, 4],
       [4, 4]])

***Selection....***

In [ ]:
m1>4  #selection based off ccomparision operators
      # it will only return boolean values

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [ ]:
m1[m1>2]

array([3, 4, 5, 6, 7, 8, 9, 9, 7, 5, 5, 6, 3, 6])

In [ ]:
m1[m1>=6]

array([6, 7, 8, 9, 9, 7, 6, 6])

In [ ]:
m1[m1==8]

array([8])

In [ ]:
# arithmetic operations

In [ ]:
m1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 9, 7, 5],
       [5, 6, 3, 6]])

In [ ]:
m2=m1+m1 #add 2 array

In [ ]:
m2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 18, 14, 10],
       [10, 12,  6, 12]])

In [ ]:
m2-m1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 9, 7, 5],
       [5, 6, 3, 6]])

In [ ]:
m1*m2

array([[  2,   8,  18,  32],
       [ 50,  72,  98, 128],
       [162, 162,  98,  50],
       [ 50,  72,  18,  72]])

In [ ]:
m2/m1

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
m1/m2

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [ ]:
m1%m2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 9, 7, 5],
       [5, 6, 3, 6]])